# As noted in the Docker best practices "each container should have only one concern
# ENTRYPOINT ["tail", "-f", "/dev/null"]
# https://learnxinyminutes.com/

# for make
#  https://github.com/uniconproject/unicon


version: "3.9"

services:

  ada:
    container_name: hello_world_ada
    build:
      context: projects/ada
      dockerfile: DockerfileAda

  arc:
    container_name: hello_world_arc
    build:
      context: projects/arc
      dockerfile: DockerfileArc

  alef:
    container_name: hello_world_alef
    build:
      context: projects/alef
      dockerfile: DockerfileAlef

  apl:
    container_name: hello_world_apl
    build:
      context: projects/apl
      dockerfile: DockerfileApl

  agda:
    container_name: hello_world_agda
    build:
      context: projects/agda
      dockerfile: DockerfileAgda

  applescript:
    container_name: hello_world_applescript
    build:
      context: projects/applescript
      dockerfile: DockerfileApplescript

  assemblyscript:
    container_name: hello_world_assemblyscript
    build:
      context: projects/assemblyscript
      dockerfile: DockerfileAssemblyscript

  actionscript:
    container_name: hello_world_actionscript
    build:
      context: projects/actionscript
      dockerfile: DockerfileActionScript

  b:
    container_name: hello_world_b
    build:
      context: projects/b
      dockerfile: DockerfileB

  bosque:
    container_name: hello_world_bosque
    build:
      context: projects/bosque
      dockerfile: DockerfileBosque

#  beta:
#    container_name: hello_world_beta
#    build:
#      context: projects/beta
#      dockerfile: DockerfileBeta

  bcpl:
    container_name: hello_world_bcpl
    build:
      context: projects/bcpl
      dockerfile: DockerfileBcpl

  blitzmax:
    container_name: hello_world_blitzmax
    build:
      context: projects/blitzmax
      dockerfile: DockerfileBlitzMax

  boo:
    container_name: hello_world_boo
    build:
      context: projects/boo
      dockerfile: DockerfileBoo

  bird:
    container_name: hello_world_bird
    build:
      context: projects/bird
      dockerfile: DockerfileBird

  cyclone:
    container_name: hello_world_cyclone
    build:
      context: projects/cyclone
      dockerfile: DockerfileCyclone

  claire4:
    container_name: hello_world_claire4
    build:
      context: projects/claire4
      dockerfile: DockerfileClaire4

  carbon:
    container_name: hello_world_carbon
    build:
      context: projects/carbon
      dockerfile: DockerfileCarbon

  #  clu:
  #    container_name: hello_world_clu
  #    build:
  #      context: projects/clu
  #      dockerfile: DockerfileClu

  cobra:
    container_name: hello_world_cobra
    build:
      context: projects/cobra
      dockerfile: DockerfileCobra

  cypher:
    container_name: hello_world_cypher
    build:
      context: projects/cypher
      dockerfile: DockerfileCypher

  cython:
    container_name: hello_world_cython
    build:
      context: projects/cython
      dockerfile: DockerfileCython
  e:
    container_name: hello_world_e
    build:
      context: projects/e
      dockerfile: DockerfileE

  evil:
    container_name: hello_world_evil
    build:
      context: projects/evil
      dockerfile: DockerfileEvil

  euclid:
    container_name: hello_world_euclid
    build:
      context: projects/euclid
      dockerfile: DockerfileEuclid

  escher:
    container_name: hello_world_escher
    build:
      context: projects/escher
      dockerfile: DockerfileEscher

  delphi:
    container_name: hello_World_delphi
    build:
      context: projects/delphi
      dockerfile: DockerfileDelphi

  eiffel:
    container_name: hello_world_eiffel
    build:
      context: projects/eiffel
      dockerfile: DockerfileEiffel

  elm:
    container_name: hellow_world_elm
    build:
      context: projects/elm
      dockerfile: DockerfileElm

  forth:
    container_name: hello_world_forth
    build:
      context: projects/forth
      dockerfile: DockerfileForth

  hack:
    container_name: hello_world_hack
    build:
      context: projects/hack
      dockerfile: DockerfileHack

  hop:
    container_name: hello_world_hop
    build:
      context: projects/hop
      dockerfile: DockerfileHop

  io:
    container_name: hello_world_io
    build:
      context: projects/io
      dockerfile: DockerfileIo

  icon:
    container_name: hello_world_icon
    build:
      context: projects/icon
      dockerfile: DockerfileIcon

  jade:
    container_name: hello_world_jade
    build:
      context: projects/jade
      dockerfile: DockerfileJade

  limbo:
    container_name: hello_world_limbo
    build:
      context: projects/limbo
      dockerfile: DockerfileLimbo

  lfe:
    container_name: hello_world_lfe
    build:
      context: projects/lfe
      dockerfile: DockerfileLfe

  logo:
    container_name: hello_world_logo
    build:
      context: projects/logo
      dockerfile: DockerfileLogo

  lasso:
    container_name: hello_world_lasso
    build:
      context: projects/lasso
      dockerfile: DockerfileLasso

  matlab:
    container_name: hello_world_matlab
    build:
      context: projects/matlab
      dockerfile: DockerfileMatlab

  mesa:
    container_name: hello_world_mesa
    build:
      context: projects/mesa
      dockerfile: DockerfileMesa

  modula:
    container_name: hello_world_modula
    build:
      context: projects/modula
      dockerfile: DockerfileModula

  modula3:
    container_name: hello_world_modula3
    build:
      context: projects/modula3
      dockerfile: DockerfileModula3

  mypy:
    container_name: hello_world_mypy
    build:
      context: projects/mypy
      dockerfile: DockerfileMypy

  newspeak:
    container_name: hello_world_newspeak
    build:
      context: projects/newspeak
      dockerfile: DockerfileNewspeak

  nu:
    container_name: hello_world_nu
    build:
      context: projects/nu
      dockerfile: DockerfileNu

  nemerle:
    container_name: hello_world_nemerle
    build:
      context: projects/nemerle
      dockerfile: DockerfileNemerle

  omega:
    container_name: hello_world_omega
    build:
      context: projects/omega
      dockerfile: DockerfileOmega

  occam:
    container_name: hello_world_occam
    build:
      context: projects/occam
      dockerfile: DockerfileOccam

  oberon:
    container_name: hello_world_oberon
    build:
      context: projects/oberon
      dockerfile: DockerfileOberon

  oberon2:
    container_name: hello_world_oberon2
    build:
      context: projects/oberon2
      dockerfile: DockerfileOberon2

  objectivec:
    container_name: hello_world_objectivec
    build:
      context: projects/objectivec
      dockerfile: DockerfileObjectivec

  oxygene:
    container_name: hello_world_oxygene
    build:
      context: projects/oxygene
      dockerfile: DockerfileOxygene

  miranda:
    container_name: hello_world_miranda
    build:
      context: projects/miranda
      dockerfile: DockerfileMiranda

  opa:
    container_name: hello_world_opa
    build:
      context: projects/opa
      dockerfile: DockerfileOpa

  parasail:
    container_name: hello_world_parasail
    build:
      context: projects/parasail
      dockerfile: DockerfileParasail

  postscript:
    container_name: hello_world_postscript
    build:
      context: projects/postscript
      dockerfile: DockerfilePostscript

  postgres:
    container_name: hello_world_postgres
#    image: postgres:bullseye
#    user: postgres
    environment:
      POSTGRES_DB: postgress
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
    build:
      context: projects/postgres
      dockerfile: DockerfilePostgres
    command:
      -

  scheme:
    container_name: hello_world_scheme
    build:
      context: projects/scheme
      dockerfile: DockerfileScheme

  self:
    container_name: hello_world_self
    build:
      context: projects/self
      dockerfile: DockerfileSelf

  seed7:
    container_name: hello_world_seed7
    build:
      context: projects/seed7
      dockerfile: DockerfileSeed7

  spark:
    container_name: hello_world_spark
    build:
      context: projects/spark
      dockerfile: DockerfileSpark

  sather:
    container_name: hello_world_sather
    build:
      context: projects/sather
      dockerfile: DockerfileSather

  sml:
    container_name: hello_world_sml
    build:
      context: projects/sml
      dockerfile: DockerfileSml

  tea:
    container_name: hello_world_tea
    build:
      context: projects/tea
      dockerfile: DockerfileTea

  turing:
    container_name: hello_world_turing
    build:
      context: projects/turing
      dockerfile: DockerfileTuring

  Typhon:
    container_name: hello_world_typhon
    build:
      context: projects/typhon
      dockerfile: DockerfileTyphon

  y:
    container_name: hello_world_y
    build:
      context: projects/y
      dockerfile: DockerfileY
