# As noted in the Docker best practices "each container should have only one concern
# CMD ["tail", "-f", "/dev/null"]

version: "3.9"

services:

  algol:
    container_name: hello_world_algol
    build:
      context: projects/algol
      dockerfile: DockerfileAlgol

  bash:
    container_name: hello_world_bash
    build:
      context: projects/bash
      dockerfile: DockerfileBash

  befunge:
    container_name: hello_world_befunge
    build:
      context: projects/befunge
      dockerfile: DockerfileBefunge

  c:
    container_name: hello_world_c
    build:
      context: projects/c
      dockerfile: DockerfileC

#  carbon:
#    container_name: hello_world_carbon
#    build:
#      context: projects/carbon
#      dockerfile: DockerfileCarbon

  cobol:
    container_name: hello_world_cobol
    build:
      context: projects/cobol
      dockerfile: DockerfileCobol

  cpp:
    container_name: hello_world_cpp
    build:
      context: projects/cpp
      dockerfile: DockerfileCpp

  crystal:
    container_name: hello_world_crystal
    build:
      context: projects/crystal
      dockerfile: DockerfileCrystal

  csharp:
    container_name: hello_world_csharp
    build:
      context: projects/csharp
      dockerfile: DockerfileCsharp

#  eiffel:
#    container_name: hello_world_eiffel
#    build:
#      context: projects/eiffel
#      dockerfile: DockerfileEiffel

#  elm:
#    container_name: hellow_world_elm
#    build:
#      context: projects/elm
#      dockerfile: DockerfileElm

  erlang:
    container_name: hello_world_erlang
    build:
      context: projects/erlang
      dockerfile: DockerfileErlang

#  forth:
#    container_name: hello_world_forth
#    build:
#      context: projects/forth
#      dockerfile: DockerfileForth

  fortran:
    container_name: hello_world_fortran
    build:
      context: projects/fortran
      dockerfile: DockerfileFortran

  golang:
    container_name: hello_world_golang
    build:
      context: projects/golang
      dockerfile: DockerfileGolang

  haskell:
    container_name: hello_world_haskell
    build:
      context: projects/haskell
      dockerfile: DockerfileHaskell

  java:
    container_name: hello_world_java
    build:
      context: projects/java
      dockerfile: DockerfileJava

  javascript:
    container_name: hello_world_javascript
    build:
      context: projects/javascript
      dockerfile: DockerfileJs

  julia:
    container_name: hello_world_julia
    build:
      context: projects/julia
      dockerfile: DockerfileJulia

  kotlin:
    container_name: hello_world_kotlin
    build:
      context: projects/kotlin
      dockerfile: DockerfileKotlin

  lisp:
    container_name: hello_world_lisp
    build:
      context: projects/lisp
      dockerfile: DockerfileLisp

#  logo:
#    container_name: hello_world_logo
#    build:
#      context: projects/logo
#      dockerfile: DockerfileLogo

#  matlab:
#    container_name: hello_world_matlab
#    build:
#      context: projects/matlab
#      dockerfile: DockerfileMatlab

  pascal:
    container_name: hello_world_pascal
    build:
      context: projects/pascal
      dockerfile: DockerfilePascal

  perl:
    container_name: hello_world_perl
    build:
      context: projects/perl
      dockerfile: DockerfilePerl

  php:
    container_name: hello_world_php
    build:
      context: projects/php
      dockerfile: DockerfilePhp

  powershell:
    container_name: hello_world_powershell
    build:
      context: projects/powershell
      dockerfile: DockerfilePowershell

  python:
    container_name: hello_world_python
    build:
      context: projects/python
      dockerfile: DockerfilePython

  r:
    container_name: hello_world_r
    build:
      context: projects/r
      dockerfile: DockerfileR

  raku:
    container_name: hello_world_raku
    build:
      context: projects/raku
      dockerfile: DockerfileRaku

  ruby:
    container_name: hello_world_ruby
    build:
      context: projects/ruby
      dockerfile: DockerfileRuby

  rust:
    container_name: hello_world_rust
    build:
      context: projects/rust
      dockerfile: DockerfileRust

  scala:
    container_name: hello_world_scala
    build:
      context: projects/scala
      dockerfile: DockerfileScala

  sh:
    container_name: hello_world_sh
    build:
      context: projects/sh
      dockerfile: DockerfileSh

  swift:
    container_name: hello_world_swift
    build:
      context: projects/swift
      dockerfile: DockerfileSwift

  typescript:
    container_name: hello_world_typescript
    build:
      context: projects/typescript
      dockerfile: DockerfileTs

  zsh:
    container_name: hello_world_zsh
    build:
      context: projects/zsh
      dockerfile: DockerfileZsh
