# As noted in the Docker best practices "each container should have only one concern

version: "3.9"
secrets:
  aws_creds:
    external: true

services:
  c:
    container_name: hello_world_c
    build:
      context: projects/c
      dockerfile: DockerfileC

  cpp:
    container_name: hello_world_cpp
    build:
      context: projects/cpp
      dockerfile: DockerfileCpp

  golang:
    container_name: hello_world_golang
    build:
      context: projects/golang
      dockerfile: DockerfileGolang

  js:
    container_name: hello_world_js
    build:
      context: projects/javascript
      dockerfile: DockerfileJs

  python:
    container_name: hello_world_python
    build:
      context: projects/python
      dockerfile: DockerfilePython

  rust:
    container_name: hello_world_rust
    build:
      context: projects/rust
      dockerfile: DockerfileRust